export const actionTypes = {
  ADD_IMAGE: "ADD_IMAGE",
  INCREMENT_COUNTER: "INCREMENT_COUNTER",
  APPROVE_IMAGE: "APPROVE_IMAGE",
  TOGGLE_IMAGE_LOADING: "TOGGLE_IMAGE_LOADING",
  SET_ERROR: "SET_ERROR",
  TOGGLE_APPROVE: "TOGGLE_APPROVE",
  TOGGLE_REJECT: "TOGGLE_REJECT",
  ENABLE_APPROVE_REJECT: "ENABLE_APPROVE_REJECT",
};

export * from "./imageActions.js";
export * from "./buttonActions.js";
